

version: 1
FILE_PATTERN: '.*RSNA_ASNR_MICCAI_BraTS(?P<year>\d*)_(?P<training_type>Training|Validation)Data(?:\\{1}|[/]{1})(?P<patient_id>BraTS\d+_\d+)(?:\\{1}|[/]{1})(?P=patient_id)_(?P<modality>flair|t1ce|t1|t2)?(?:_)?(?P<info>\w*)?(?P<suffix>\.nii\.gz|\.csv|\.*)'
# used when gen path (by re.sub) from a base existed and correct path 
BASE_PATTERN: r'.*(?P<patient_id>BraTS\d+_\d+)(?:_)(?P<modality>flair|t1ce|t1|t2)(?P<suffix>\.nii\.gz)' 
# used when gen path (by re.sub) from a base existed and correct path 
REPL_BASE_PATTERN: r'\g<patient_id>_{}\g<suffix>' 
TAGS: !!python/tuple ['training_type','patient_id','modality','info']
# info: !!python/tuple [1,2]
TAGS_ORDERS: (('Training','Validation'),None,('flair','t1','t1ce','t2'),None) # used for sort
AXES_FORMAT: ('coronal', 'sagittal', 'vertical')
AXES_DIRECTION_FORMAT: ("R:L", "A:P", "I:S")
SIZE: (240,240,155)